export const auditFixture = {
  audit_id: 'audit_e2e_1',
  domain: 'example.com',
  mode: 'site',
  created_at: '2026-07-16T08:00:00.000Z',
  audit_context: {
    site_archetype: 'personal_blog',
    industry_vertical: 'technology',
    business_model: 'independent publishing',
    entity: { name: 'Example Author', type: 'Person' },
    locale: 'en',
    root_domain: 'example.com',
    confidence: 0.92,
    evidence: [{ source: 'JSON-LD', page_url: 'https://example.com/', value: 'Person: Example Author' }],
  },
  pages_audited: [
    { url: 'https://example.com/', page_type: 'home', status: 'complete' },
    { url: 'https://example.com/about', page_type: 'about', status: 'complete' },
  ],
  checks: [
    {
      id: 'seo.title',
      category: 'seo',
      title: { en: 'Document title', zh: '文档标题' },
      status: 'pass',
      severity: 'major',
      weight: 2,
      source: 'HTML parse',
      evidence: ['A descriptive title is present.'],
      page_url: 'https://example.com/',
    },
    {
      id: 'geo.author_attribution',
      category: 'geo',
      title: { en: 'Author attribution', zh: '作者归属' },
      status: 'fail',
      severity: 'critical',
      weight: 2,
      source: 'HTML and JSON-LD',
      evidence: ['The article page does not link the visible author to a Person entity.'],
      page_url: 'https://example.com/post',
    },
    {
      id: 'geo.predicted_visibility',
      category: 'geo',
      title: { en: 'Predicted visibility', zh: '预测可见性' },
      status: 'unknown',
      severity: 'info',
      weight: 0,
      source: 'Predicted',
      evidence: ['Informational simulation only.'],
    },
  ],
  recommendations_v2: [
    {
      id: 'geo.author_attribution',
      title: { en: 'Connect the visible author to a Person entity', zh: '将可见作者连接到 Person 实体' },
      severity: 'critical',
      page_url: 'https://example.com/post',
      evidence: 'The article page does not link the visible author to a Person entity.',
      why: { en: 'Answer systems cannot reliably resolve who wrote the page.', zh: '答案系统无法可靠判断页面作者。' },
      fix: { en: 'Add an author link and matching Person JSON-LD.', zh: '添加作者链接和对应的 Person JSON-LD。' },
      verify: { en: 'Validate the schema and rerun the URL audit.', zh: '验证结构化数据并重新运行单 URL 审计。' },
    },
  ],
  score_summary: {
    score_version: '2.4.0',
    status: 'complete',
    overall: {
      score: 49,
      raw_score: 67,
      coverage: 0.9,
      confidence: 0.92,
      cap: 49,
      cap_reasons: [{ code: 'CRITICAL_FAILURE', cap: 49, check_ids: ['geo.author_attribution'] }],
    },
    seo: { score: 100, raw_score: 100, coverage: 1, confidence: 0.95, cap: 100, cap_reasons: [] },
    geo: {
      score: 49,
      raw_score: 0,
      coverage: 0.8,
      confidence: 0.9,
      cap: 49,
      cap_reasons: [{ code: 'CRITICAL_FAILURE', cap: 49, check_ids: ['geo.author_attribution'] }],
    },
  },
  modules: {},
};

export const evidenceMapFixture = {
  status: 'complete',
  observed_at: '2026-07-16T08:05:00.000Z',
  affects_score: false,
  target: { appearances: 1, observed_queries: ['Example Author blog'] },
  query_plan: { queries: [{ query: 'Example Author blog', intent: 'branded' }] },
  opportunities: [],
  diagnosis: [{ stage: 'retrieval', status: 'pass', evidence: ['The audited root appeared once.'] }],
  sources: [{
    title: 'Example Author',
    canonical_url: 'https://example.com/',
    provider: 'search-api-a',
    provider_rank: 1,
    source_type: 'audited_site',
    domain: 'example.com',
    retrieved_at: '2026-07-16T08:05:00.000Z',
  }],
  search_snapshot: {
    provider_runs: [{ provider: 'search-api-a', status: 'complete', result_count: 1, latency_ms: 25, cache_hit: false }],
  },
  limitations: ['Search snapshots do not prove consumer answer citations.'],
};
